Julio Veganos e Hijos interface: Sensor Class Reference
Sensor Class Reference
#include <Sensor.h>
Public Member Functions
Sensor ()
void turnOn ()
void turnOff ()
virtual void getInfo ()
Private Attributes
bool state = true
Detailed Description
Definition at line 15 of file Sensor.h.
Constructor & Destructor Documentation
Sensor()
Sensor::Sensor ()
Definition at line 5 of file Sensor.cpp.
 {} //we define the constructor
Member Function Documentation
getInfo()
void Sensor::getInfo () virtual
Displays the sensor info (polymorphism)
Reimplemented in TemperatureSensor, LigthLevelSensor, HumiditySensor, and AirConditionSensor.
Definition at line 27 of file Sensor.cpp.
 {}
Referenced by Dashboard::showSensorChoices().
turnOff()
void Sensor::turnOff ()
Depending on the state of the sensor, we turn it off and indicate its state
Definition at line 17 of file Sensor.cpp.
                      {
   //Depending on the state of the sensor, we turn it off and indicate its state
   if (state == true){
     cout << "\nSensor Status: Off" << endl;
     state = false;
   }else{
     cout << "\nThe sensor is already off" << endl;
   }
 }
Referenced by Dashboard::showSensorChoices().
turnOn()
void Sensor::turnOn ()
Depending on the state of the sensor, we turn it on and indicate its state
Definition at line 7 of file Sensor.cpp.
                     {
   //Depending on the state of the sensor, we turn it on and indicate its state
   if (state == false){
     cout << "\nSensor status: On" << endl;
     state = true;
   }else{
     cout << "\nThe sensor is already on" << endl;
   }
 }
Referenced by Dashboard::showSensorChoices().
Member Data Documentation
state
bool Sensor::state = true private
Definition at line 37 of file Sensor.h.
The documentation for this class was generated from the following files:
Sensor.h
Sensor.cpp