Julio Veganos e Hijos interface: Dashboard Class Reference
Dashboard Class Reference
#include <Dashboard.h>
Public Member Functions
void showMenu ()
bool getOption ()
void showSensorChoices (Sensor *)
void showCameraChoices (Camera *)
Dashboard (Dashboard &otherDashboard)=delete
void operator= (const Dashboard &)=delete
Static Public Member Functions
static Dashboard * getDashboard ()
Protected Member Functions
Dashboard ()
Private Attributes
int option
int choice
Login L
DataBase D
TemperatureSensor * T = new TemperatureSensor()
HumiditySensor * H = new HumiditySensor()
LigthLevelSensor * Li = new LigthLevelSensor()
AirConditionSensor * A = new AirConditionSensor()
RGBCamera * RC = new RGBCamera()
ThermalCamera * TC = new ThermalCamera()
Microphone M
Static Private Attributes
static Dashboard * singleDashboard = nullptr
Detailed Description
Definition at line 16 of file Dashboard.h.
Constructor & Destructor Documentation
Dashboard() [1/2]
Dashboard::Dashboard (Dashboard & otherDashboard) delete
Dashboard() [2/2]
Dashboard::Dashboard () protected
Definition at line 20 of file Dashboard.cpp.
                     { //we define the constructor
   this -> option = option;
 }
Member Function Documentation
getDashboard()
Dashboard * Dashboard::getDashboard () static
Definition at line 225 of file Dashboard.cpp.
{
   if(singleDashboard == nullptr){
     singleDashboard = new Dashboard();
   }else{
     cout << "Error: trying to get another instance of a Ball singleton class!\n";
   }
   return singleDashboard;
 }
Referenced by main().
getOption()
bool Dashboard::getOption ()
Depending on the option entered, performs an action
Definition at line 119 of file Dashboard.cpp.
{
   //depending on the option entered, performs an action
   cout << "Enter the number of the action you want to do: ";
   cin >> option;
   switch (option)
   {
     case 1:
       system("clear");
       showSensorChoices(T);
       break;
     case 2:
       system("clear");
       showSensorChoices(H);
       break;
     case 3:
       system("clear");
       showSensorChoices(Li);
       break;
     case 4:
       system("clear");
       showSensorChoices(A);
       break;
     case 5:
       system("clear");
       showCameraChoices(RC);
       break;
     case 6:
       system("clear");
       showCameraChoices(TC);
       break;
     case 7:
       system("clear");
       M.showChoice();
       break;
     case 8:
       return true;
       break;
     case 9:
       D.saveFile();
       exit(EXIT_SUCCESS);
       break;
     case 10:
       system("clear");
       D.showAdminChoices();
       break;
   }
   return false;
 }
operator=()
void Dashboard::operator= (const Dashboard &) delete
showCameraChoices()
void Dashboard::showCameraChoices (Camera * camera)
Displays the camera options menu and performs the action depending on the option entered
Definition at line 72 of file Dashboard.cpp.
{
   //displays the temperature sensor options menu
   while (true) {
     cout << "                               __  __  _____  _   _  _   _ " << endl
           << "                              |  \\/  || ____|| \\ | || | | |" << endl
           << "                              | |\\/| ||  _|  |  \\| || | | |" << endl
           << "                              | |  | || |___ | |\\  || |_| |" << endl
           << "                              |_|  |_||_____||_| \\_| \\___/ " << endl
           << "                                                                             " << endl
           << "-----------------------------------------------------------------------------------------------" << endl
           << "ººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººº\n" << endl;
     cout << "                                   1. TURN ON" << endl
         << "                                   2. TURN OFF" << endl
         << "                                   3. SHOW DATA INFO" << endl
         << "                                   4. BACK TO MENU" << endl;
     cout << "\nEnter your choice number: ";
     cin >> choice;
     //Depending on the option that is entered, it calls its respective function
     switch (choice)
     {
     case 1:
       camera->turnOn();
       system("sleep 3");
       system("clear");
       break;
     case 2:
       camera->turnOff();
       system("sleep 3");
       system("clear");
       break;
     case 3:
       camera->getInfo();
       system("sleep 3");
       system("clear");
       break;
     case 4:
       //go back to the main menu
       return;
       break;
     }
   }
 }
References Camera::getInfo(), Camera::turnOff(), and Camera::turnOn().
showMenu()
void Dashboard::showMenu ()
Displays the login screen and, depending on whether the user exists, displays the main menu Checks that the user entered is of type Admin Allows the showMenu() function to be called again when you want to log out and re-enter a user in case of not putting it, it does not verify that the user exists
Definition at line 178 of file Dashboard.cpp.
{
     try{
       //displays the login screen and, depending on whether the user exists, displays the main menu
       if (L.checkLogin(&D)){
         while (true){
           system("clear");
           cout << "               __  __     _     ___  _   _       __  __  _____  _   _  _   _ " << endl
           << "              |  \\/  |   / \\   |_ _|| \\ | |     |  \\/  || ____|| \\ | || | | |" << endl
           << "              | |\\/| |  / _ \\   | | |  \\| |     | |\\/| ||  _|  |  \\| || | | |" << endl
           << "              | |  | | / ___ \\  | | | |\\  |     | |  | || |___ | |\\  || |_| |" << endl
           << "              |_|  |_|/_/   \\_\\|___||_| \\_|     |_|  |_||_____||_| \\_| \\___/ " << endl
           << "                                                                             " << endl
           << "-----------------------------------------------------------------------------------------------" << endl
           << "ººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººº\n" << endl;
           cout << "                                   1. TEMPERATURE SENSOR" << endl << "                                   2. HUMIDITY SENSOR" << endl
           << "                                   3. LIGTH LEVEL SENSOR" << endl << "                                   4. AIR CONDITION SENSOR" << endl
           << "                                   5. RGB CAMERA" << endl << "                                   6. THERMAL CAMERA" << endl
           << "                                   7. MICROPHONE" << endl << "                                   8. SIGN OFF" << endl
           << "                                   9. EXIT" << endl;
           //checks that the user entered is of type Admin
           if(D.userNow.checkAdmin()){
             cout << "                                   10. MANAGE USERS\n" << endl;
           }
           //allows the showMenu() function to be called again when you want to log out and re-enter a user
           //in case of not putting it, it does not verify that the user exists
           if (getOption()){
             return;
           }
         }
       }
     }
     catch(UserNumException &except){
       cout << "Exception: " << except.what() << endl;
     }
     catch(NIFException &except){
       cout << "Exception: " << except.what() << endl;
     }
 }
showSensorChoices()
void Dashboard::showSensorChoices (Sensor * sensor)
Displays the sensor options menu and performs the action depending on the option entered
Definition at line 24 of file Dashboard.cpp.
{
   //displays the temperature sensor options menu
   while (true) {
     cout << "                               __  __  _____  _   _  _   _ " << endl
           << "                              |  \\/  || ____|| \\ | || | | |" << endl
           << "                              | |\\/| ||  _|  |  \\| || | | |" << endl
           << "                              | |  | || |___ | |\\  || |_| |" << endl
           << "                              |_|  |_||_____||_| \\_| \\___/ " << endl
           << "                                                                             " << endl
           << "-----------------------------------------------------------------------------------------------" << endl
           << "ººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººº\n" << endl;
     cout << "                                   1. TURN ON" << endl
         << "                                   2. TURN OFF" << endl
         << "                                   3. SHOW DATA INFO" << endl
         << "                                   4. BACK TO MENU" << endl;
     cout << "\nEnter your choice number: ";
     cin >> choice;
     //Depending on the option that is entered, it calls its respective function
     switch (choice)
     {
     case 1:
       sensor->turnOn();
       system("sleep 3");
       system("clear");
       break;
     case 2:
       sensor->turnOff();
       system("sleep 3");
       system("clear");
       break;
     case 3:
       sensor->getInfo();
       cout.flush();
       system("sleep 3");
       system("clear");
       break;
     case 4:
       //go back to the main menu
       return;
       break;
     }
   }
 }
References Sensor::getInfo(), Sensor::turnOff(), and Sensor::turnOn().
Member Data Documentation
A
AirConditionSensor* Dashboard::A = new AirConditionSensor() private
Definition at line 61 of file Dashboard.h.
choice
int Dashboard::choice private
Definition at line 53 of file Dashboard.h.
D
DataBase Dashboard::D private
Definition at line 57 of file Dashboard.h.
H
HumiditySensor* Dashboard::H = new HumiditySensor() private
Definition at line 59 of file Dashboard.h.
L
Login Dashboard::L private
Definition at line 56 of file Dashboard.h.
Li
LigthLevelSensor* Dashboard::Li = new LigthLevelSensor() private
Definition at line 60 of file Dashboard.h.
M
Microphone Dashboard::M private
Definition at line 64 of file Dashboard.h.
option
int Dashboard::option private
Definition at line 52 of file Dashboard.h.
RC
RGBCamera* Dashboard::RC = new RGBCamera() private
Definition at line 62 of file Dashboard.h.
singleDashboard
Dashboard * Dashboard::singleDashboard = nullptr static private
Definition at line 54 of file Dashboard.h.
T
TemperatureSensor* Dashboard::T = new TemperatureSensor() private
Definition at line 58 of file Dashboard.h.
TC
ThermalCamera* Dashboard::TC = new ThermalCamera() private
Definition at line 63 of file Dashboard.h.
The documentation for this class was generated from the following files:
Dashboard.h
Dashboard.cpp