Julio Veganos e Hijos interface: HumiditySensor Class Reference
HumiditySensor Class Reference
#include <HumiditySensor.h>
Public Member Functions
HumiditySensor ()
void checkHumidity ()
void getHumidity ()
void showChoice ()
Public Member Functions inherited from Sensor
Sensor ()
void turnOn ()
void turnOff ()
Private Attributes
float humidity
int choice
Detailed Description
Definition at line 17 of file HumiditySensor.h.
Constructor & Destructor Documentation
HumiditySensor()
HumiditySensor::HumiditySensor ()
Definition at line 9 of file HumiditySensor.cpp.
 :Sensor() {} //we define the constructor indicating that it is an inherit class of sensor
Member Function Documentation
checkHumidity()
void HumiditySensor::checkHumidity ()
Creates a random number to simulate de current humidity
Definition at line 11 of file HumiditySensor.cpp.
{
   //create a random number
   srand(time(NULL)+1);
   humidity = rand()%101;
 }
References humidity.
Referenced by getHumidity().
getHumidity()
void HumiditySensor::getHumidity ()
Displays the current humidity created with checkHumidity()
Definition at line 17 of file HumiditySensor.cpp.
{
   //displays the current humidity created with checkHumidity()
   checkHumidity();
   cout << "\nCurrent humidity: " << humidity << "%" << endl;
 }
References checkHumidity(), and humidity.
Referenced by showChoice().
showChoice()
void HumiditySensor::showChoice ()
Displays the humidity sensor options menu Depending on the option that is entered, it calls its respective function
Definition at line 23 of file HumiditySensor.cpp.
{
   //displays the humidity sensor options menu
   while (true) {
     cout << "\n                _   _                    _      _  _  _          " << endl
     << "               | | | |                  (_)    | |(_)| |         " << endl
     << "               | |_| | _   _  _ __ ___   _   __| | _ | |_  _   _ " << endl
     << "               |  _  || | | || '_ ` _ \\ | | / _` || || __|| | | |" << endl
     << "               | | | || |_| || | | | | || || (_| || || |_ | |_| |" << endl
     << "               \\_| |_/ \\__,_||_| |_| |_||_| \\__,_||_| \\__| \\__, |" << endl
     << "                                                            __/ |" << endl
     << "                                                           |___/ " << endl
     << "                                                                 " <<endl
     << "-----------------------------------------------------------------------------------------------" << endl
     << "ººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººº\n" << endl;
     cout << "                                   1. TURN ON" << endl
         << "                                   2. TURN OFF" << endl
         << "                                   3. SHOW CURRENT HUMIDITY" << endl
         << "                                   4. BACK TO MENU" << endl;
     cout << "Enter your choice number: ";
     cin >> choice;
     //Depending on the option that is entered, it calls its respective function
     switch (choice)
     {
     case 1:
       Sensor::turnOn();
       system("sleep 3");
       system("clear");
       break;
     case 2:
       Sensor::turnOff();
       system("sleep 3");
       system("clear");
       break;
     case 3:
       getHumidity();
       system("sleep 3");
       system("clear");
       break;
     case 4:
       //go back to the main menu
       return;
       break;
     }
   }
 }
References choice, getHumidity(), Sensor::turnOff(), and Sensor::turnOn().
Member Data Documentation
choice
int HumiditySensor::choice private
Definition at line 41 of file HumiditySensor.h.
Referenced by showChoice().
humidity
float HumiditySensor::humidity private
Definition at line 40 of file HumiditySensor.h.
Referenced by checkHumidity(), and getHumidity().
The documentation for this class was generated from the following files:
HumiditySensor.h
HumiditySensor.cpp