Julio Veganos e Hijos interface: TemperatureSensor Class Reference
TemperatureSensor Class Reference
#include <TemperatureSensor.h>
Public Member Functions
TemperatureSensor ()
void checkTemperature ()
void getTemp ()
void showChoice ()
Public Member Functions inherited from Sensor
Sensor ()
void turnOn ()
void turnOff ()
Private Attributes
float temperature
int choice
Detailed Description
Definition at line 17 of file TemperatureSensor.h.
Constructor & Destructor Documentation
TemperatureSensor()
TemperatureSensor::TemperatureSensor ()
Definition at line 9 of file TemperatureSensor.cpp.
 :Sensor() {} //we define the constructor indicating that it is an inherit class of sensor
Member Function Documentation
checkTemperature()
void TemperatureSensor::checkTemperature ()
Creates a random number to simulate de current temperature
Definition at line 11 of file TemperatureSensor.cpp.
{
   //create a random number
   srand(time(NULL));
   temperature = 25+rand()%(40 +1 - 25);
 }
References temperature.
Referenced by getTemp().
getTemp()
void TemperatureSensor::getTemp ()
Displays the current temperature created with checkTemperature()
Definition at line 17 of file TemperatureSensor.cpp.
{
   //displays the current temperature created with checkTemperature()
   checkTemperature();
   cout << "\nCurrent temperature: " << temperature << " ºC" << endl;
 }
References checkTemperature(), and temperature.
Referenced by showChoice().
showChoice()
void TemperatureSensor::showChoice ()
Displays the temperature sensor options menu Depending on the option that is entered, it calls its respective function
Definition at line 23 of file TemperatureSensor.cpp.
{
   //displays the temperature sensor options menu
   while (true) {
     cout << "\n                _____                                          _                     " << endl
     << "               |_   _|                                        | |                    " << endl
     << "                 | |  ___  _ __ ___   _ __    ___  _ __  __ _ | |_  _   _  _ __  ___ " << endl
     << "                 | | / _ \\| '_ ` _ \\ | '_ \\  / _ \\| '__|/ _` || __|| | | || '__|/ _ \\" << endl
     << "                 | ||  __/| | | | | || |_) ||  __/| |  | (_| || |_ | |_| || |  |  __/" << endl
     << "                 \\_/ \\___||_| |_| |_|| .__/  \\___||_|   \\__,_| \\__| \\__,_||_|   \\___|" << endl
     << "                                     | |                                             " << endl
     << "                                     |_|                                             " << endl
     << "                                                                                     " << endl
     << "-----------------------------------------------------------------------------------------------" << endl
     << "ººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººº\n" << endl;
     cout << "                                   1. TURN ON" << endl
         << "                                   2. TURN OFF" << endl
         << "                                   3. SHOW CURRENT TEMPERATURE" << endl
         << "                                   4. BACK TO MENU" << endl;
     cout << "\nEnter your choice number: ";
     cin >> choice;
     //Depending on the option that is entered, it calls its respective function
     switch (choice)
     {
     case 1:
       Sensor::turnOn();
       system("sleep 3");
       system("clear");
       break;
     case 2:
       Sensor::turnOff();
       system("sleep 3");
       system("clear");
       break;
     case 3:
       getTemp();
       system("sleep 3");
       system("clear");
       break;
     case 4:
       //go back to the main menu
       return;
       break;
     }
   }
 }
References choice, getTemp(), Sensor::turnOff(), and Sensor::turnOn().
Member Data Documentation
choice
int TemperatureSensor::choice private
Definition at line 42 of file TemperatureSensor.h.
Referenced by showChoice().
temperature
float TemperatureSensor::temperature private
Definition at line 41 of file TemperatureSensor.h.
Referenced by checkTemperature(), and getTemp().
The documentation for this class was generated from the following files:
TemperatureSensor.h
TemperatureSensor.cpp