Julio Veganos e Hijos interface: AirConditionSensor Class Reference
AirConditionSensor Class Reference
#include <AirConditionSensor.h>
Public Member Functions
AirConditionSensor ()
void checkAirCondition ()
void getAirCondition ()
void showChoice ()
Public Member Functions inherited from Sensor
Sensor ()
void turnOn ()
void turnOff ()
Private Attributes
float airCondition
int choice
Detailed Description
Definition at line 17 of file AirConditionSensor.h.
Constructor & Destructor Documentation
AirConditionSensor()
AirConditionSensor::AirConditionSensor ()
Definition at line 9 of file AirConditionSensor.cpp.
 :Sensor() {} //we define the constructor indicating that it is an inherit class of sensor
Member Function Documentation
checkAirCondition()
void AirConditionSensor::checkAirCondition ()
Creates a random number to simulate de current air condition
Definition at line 11 of file AirConditionSensor.cpp.
{
   //create a random number
   srand(time(NULL)+3);
   airCondition = rand()%301;
 }
References airCondition.
Referenced by getAirCondition().
getAirCondition()
void AirConditionSensor::getAirCondition ()
Displays the current ligth level created with checkLigthLevel()
Definition at line 17 of file AirConditionSensor.cpp.
{
   //displays the current ligth level created with checkLigthLevel()
   checkAirCondition();
   cout << "\nCurrent air condition level: " << airCondition << " ppm" << endl;
 }
References airCondition, and checkAirCondition().
Referenced by showChoice().
showChoice()
void AirConditionSensor::showChoice ()
Displays the air condition sensor options menu. Depending on the option that is entered, it calls its respective function.
Definition at line 23 of file AirConditionSensor.cpp.
{
   //displays the air condition sensor options menu
   while (true) {
     cout << "\n                ___   _                                _  _  _    _               " << endl
     << "               / _ \\ (_)                              | |(_)| |  (_)              " << endl
     << "              / /_\\ \\ _  _ __    ___  ___   _ __    __| | _ | |_  _   ___   _ __  " << endl
     << "              |  _  || || '__|  / __|/ _ \\ | '_ \\  / _` || || __|| | / _ \\ | '_ \\ " << endl
     << "              | | | || || |    | (__| (_) || | | || (_| || || |_ | || (_) || | | |" << endl
     << "              \\_| |_/|_||_|     \\___|\\___/ |_| |_| \\__,_||_| \\__||_| \\___/ |_| |_|" << endl
     << "                                                                                  " << endl
     << "-----------------------------------------------------------------------------------------------" << endl
     << "ººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººº\n" << endl;
     cout << "                                   1. TURN ON" << endl
         << "                                   2. TURN OFF" << endl
         << "                                   3. SHOW CURRENT AIR CONDITION" << endl
         << "                                   4. BACK TO MENU" << endl;
     cout << "Enter your choice number: ";
     cin >> choice;
     //Depending on the option that is entered, it calls its respective function
     switch (choice)
     {
     case 1:
       Sensor::turnOn();
       system("sleep 3");
       system("clear");
       break;
     case 2:
       Sensor::turnOff();
       system("sleep 3");
       system("clear");
       break;
     case 3:
       getAirCondition();
       system("sleep 3");
       system("clear");
       break;
     case 4:
       //go back to the main menu
       return;
       break;
     }
   }
 }
References choice, getAirCondition(), Sensor::turnOff(), and Sensor::turnOn().
Member Data Documentation
airCondition
float AirConditionSensor::airCondition private
Definition at line 41 of file AirConditionSensor.h.
Referenced by checkAirCondition(), and getAirCondition().
choice
int AirConditionSensor::choice private
Definition at line 42 of file AirConditionSensor.h.
Referenced by showChoice().
The documentation for this class was generated from the following files:
AirConditionSensor.h
AirConditionSensor.cpp