Julio Veganos e Hijos interface: User Class Reference
User Class Reference
#include <User.h>
Public Member Functions
User ()
User (float userNumber, float NIF, string name, bool isAdmin)
int getUserNum ()
int getNIF ()
bool checkAdmin ()
string getUserName ()
void showUser ()
bool operator< (const User &) const
Private Attributes
int userNumber
int NIF
char name [10]
bool isAdmin
Detailed Description
Definition at line 15 of file User.h.
Constructor & Destructor Documentation
User() [1/2]
User::User ()
Definition at line 9 of file User.cpp.
 {} //we define the default constructor
User() [2/2]
User::User (float userNumber, float NIF, string name, bool isAdmin)
Definition at line 11 of file User.cpp.
                                                                  { //we define the constructor with parameters
   this -> userNumber = userNumber;
   this -> NIF = NIF;
   strcpy(this->name,name.c_str());
   this -> isAdmin = isAdmin;
 };
Member Function Documentation
checkAdmin()
bool User::checkAdmin ()
Returns if a user is admin o not by true or false
Definition at line 31 of file User.cpp.
                      {
   return isAdmin;
 }
Referenced by DataBase::showUsers().
getNIF()
int User::getNIF ()
Returns the NIF
Definition at line 24 of file User.cpp.
                 {
   if (NIF < 9999999 || NIF > 99999999){
     throw NIFException();
   }
   return NIF;
 }
Referenced by DataBase::checkUser().
getUserName()
string User::getUserName ()
Returns the user name
Definition at line 35 of file User.cpp.
{
   return name;
 }
getUserNum()
int User::getUserNum ()
Returns the user number
Definition at line 18 of file User.cpp.
                     {
   if (userNumber < 1 || userNumber > 99999){
     throw UserNumException();
   }
   return userNumber;
 }
Referenced by DataBase::checkUser(), and DataBase::deleteUser().
operator<()
bool User::operator< (const User & user) const
Overloads the < operator to compare in the set
Definition at line 43 of file User.cpp.
{
   return userNumber < user.userNumber;
 }
References userNumber.
showUser()
void User::showUser ()
Returns the user name
Definition at line 39 of file User.cpp.
                    {
   cout << userNumber << "\t" << name;
 }
Referenced by DataBase::showUsers().
Member Data Documentation
isAdmin
bool User::isAdmin private
Definition at line 56 of file User.h.
name
char User::name[10] private
Definition at line 55 of file User.h.
NIF
int User::NIF private
Definition at line 54 of file User.h.
userNumber
int User::userNumber private
Definition at line 53 of file User.h.
Referenced by operator<().
The documentation for this class was generated from the following files:
User.h
User.cpp