Julio Veganos e Hijos interface: LigthLevelSensor Class Reference
LigthLevelSensor Class Reference
#include <LigthLevelSensor.h>
Public Member Functions
LigthLevelSensor ()
void checkLigthLevel ()
void getLigthLevel ()
void showChoice ()
Public Member Functions inherited from Sensor
Sensor ()
void turnOn ()
void turnOff ()
Private Attributes
float ligthLevel
int choice
Detailed Description
Definition at line 17 of file LigthLevelSensor.h.
Constructor & Destructor Documentation
LigthLevelSensor()
LigthLevelSensor::LigthLevelSensor ()
Definition at line 9 of file LigthLevelSensor.cpp.
 :Sensor() {} //we define the constructor indicating that it is an inherit class of sensor
Member Function Documentation
checkLigthLevel()
void LigthLevelSensor::checkLigthLevel ()
Creates a random number to simulate de current ligth level
Definition at line 11 of file LigthLevelSensor.cpp.
{
   //create a random number
   srand(time(NULL)+2);
   ligthLevel = rand()%101;
 }
References ligthLevel.
Referenced by getLigthLevel().
getLigthLevel()
void LigthLevelSensor::getLigthLevel ()
Displays the current ligth level created with checkLigthLevel()
Definition at line 17 of file LigthLevelSensor.cpp.
{
   //displays the current ligth level created with checkLigthLevel()
   checkLigthLevel();
   cout << "\nCurrent ligth level: " << ligthLevel << "%" << endl;
 }
References checkLigthLevel(), and ligthLevel.
Referenced by showChoice().
showChoice()
void LigthLevelSensor::showChoice ()
Displays the ligth level sensor options menu Depending on the option that is entered, it calls its respective function
Definition at line 23 of file LigthLevelSensor.cpp.
{
   //displays the ligth level sensor options menu
   while (true) {
     cout << "\n                _      _         _    _       _                    _ " << endl
     << "               | |    (_)       | |  | |     | |                  | |" << endl
     << "               | |     _   __ _ | |_ | |__   | |  ___ __   __ ___ | |" << endl
     << "               | |    | | / _` || __|| '_ \\  | | / _ \\  \\ / // _ \\| |" << endl
     << "               | |____| || (_| || |_ | | | | | ||  __/ \\ V /|  __/| |" << endl
     << "               \\_____/|_| \\__, | \\__||_| |_| |_| \\___|  \\_/  \\___||_|" << endl
     << "                           __/ |                                     " << endl
     << "                          |___/                                      " << endl
     << "                                                                     " << endl
     << "-----------------------------------------------------------------------------------------------" << endl
     << "ººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººººº\n" << endl;
     cout << "                                   1. TURN ON" << endl
         << "                                   2. TURN OFF" << endl
         << "                                   3. SHOW CURRENT LIGTH LEVEL" << endl
         << "                                   4. BACK TO MENU" << endl;
     cout << "Enter your choice number: ";
     cin >> choice;
     //Depending on the option that is entered, it calls its respective function
     switch (choice)
     {
     case 1:
       Sensor::turnOn();
       system("sleep 3");
       system("clear");
       break;
     case 2:
       Sensor::turnOff();
       system("sleep 3");
       system("clear");
       break;
     case 3:
       getLigthLevel();
       system("sleep 3");
       system("clear");
       break;
     case 4:
       //go back to the main menu
       return;
       break;
     }
   }
 }
References choice, getLigthLevel(), Sensor::turnOff(), and Sensor::turnOn().
Member Data Documentation
choice
int LigthLevelSensor::choice private
Definition at line 41 of file LigthLevelSensor.h.
Referenced by showChoice().
ligthLevel
float LigthLevelSensor::ligthLevel private
Definition at line 40 of file LigthLevelSensor.h.
Referenced by checkLigthLevel(), and getLigthLevel().
The documentation for this class was generated from the following files:
LigthLevelSensor.h
LigthLevelSensor.cpp