Julio Veganos e Hijos interface: DataBase Class Reference
DataBase Class Reference
#include <DataBase.h>
Public Member Functions
DataBase ()
bool checkUser (int, int)
void addUser (string, string, string, bool)
void deleteUser (int)
void showUsers ()
void showAdminChoices ()
void saveFile ()
Public Attributes
User userNow
User userDeleted
Private Attributes
set< User > dataBaseUser
set< User >::iterator it
int choice
std::string userNumberStr
std::string NIFStr
int userNumber
int NIF
string name
int type
bool isAdmin
Detailed Description
Definition at line 18 of file DataBase.h.
Constructor & Destructor Documentation
DataBase()
DataBase::DataBase ()
Definition at line 17 of file DataBase.cpp.
                    { //we define the constructor with the initial users that we are gonna have
   /*this->dataBaseUser.insert(User(1,13172409,"Ana",true));
   this->dataBaseUser.insert(User(2,13172408,"Paula",false));
   this->dataBaseUser.insert(User(3,12345678,"Carlos",false));*/
   // Reads the users found in the users.dat file and dumps them into the database set
   ifstream inUsersFile ("users.dat", ios::in | ios::binary);
   if (!inUsersFile) { // fstream could not open file
     cerr << "File could not be opened." << endl;
     exit (1);
   }
   User user;
   inUsersFile.read (reinterpret_cast <char *>(&user), sizeof (User));
   while (inUsersFile && !inUsersFile.eof()) {
     this->dataBaseUser.insert(user);
     inUsersFile.read (reinterpret_cast <char *>(&user), sizeof (User));
   }
 }
Member Function Documentation
addUser()
void DataBase::addUser (string userNumberStr, string NIFStr, string name, bool isAdmin)
Checks that both the user number and password are the correct size Adds a new user that is entered by an admin in the terminal
Definition at line 55 of file DataBase.cpp.
{
   //checks that both the user number and password are the correct size
   try{
     for(int n = 0; n < userNumberStr.length(); n++){
       if(int(userNumberStr[n]) < 47 || int(userNumberStr[n] > 57)){
         throw StringException();
       }
       userNumber = stoi(userNumberStr);
     }
     if (userNumber < 1 || userNumber > 99999){
       throw UserNumException();
     }
     for(int n = 0; n < NIFStr.length(); n++){
       if(int(NIFStr[n]) < 47 || int(NIFStr[n] > 57)){
         throw StringException();
       }
       NIF = stoi(NIFStr);
     }
     if (NIF < 9999999 || NIF > 99999999){
       throw NIFException();
     }
     if(isAdmin != 1 && isAdmin != 0){
       throw TypeError();
     }
     //adds a new user that is entered by an admin in the terminal
     this->dataBaseUser.insert(User(userNumber, NIF, name, isAdmin));
   }
   catch(UserNumException &except){
     cout << "Exception: " << except.what() << endl;
   }
   catch(NIFException &except){
     cout << "Exception: " << except.what() << endl;
   }
   catch(TypeError &except){
     cout << "Exception: " << except.what() << endl;
   }
   catch(StringException &except){
     cout << "Exception: " << except.what() << endl;
   }
 }
checkUser()
bool DataBase::checkUser (int userNumber, int NIF)
Checks if the user exixts
Definition at line 38 of file DataBase.cpp.
{
   bool authentication = false;
   //checks if the user exixts
   do{
     for(it=dataBaseUser.begin(); it!=dataBaseUser.end(); it++){
       User user = *it;
       if(userNumber==user.getUserNum() && NIF==user.getNIF()){
           userNow = user;
           return true;
           authentication = true;
       }
     }
   }while(authentication == false);
   return false;
 }
References User::getNIF(), and User::getUserNum().
Referenced by Login::checkLogin().
deleteUser()
void DataBase::deleteUser (int userNumber)
Deletes the user that is entered by an admin in the terminal
Definition at line 105 of file DataBase.cpp.
{
   //deletes the user that is entered by an admin in the terminal
   for(it=dataBaseUser.begin(); it!=dataBaseUser.end(); it++){
     User user = *it;
     if(userNumber==user.getUserNum()){
       userDeleted = user;
     }
   }
   this->dataBaseUser.erase(userDeleted);
   cout << "El usuario ha sido eliminado" << endl;
 }
References User::getUserNum().
saveFile()
void DataBase::saveFile ()
Saves the users found in the set to the file users.dat
Definition at line 181 of file DataBase.cpp.
{
   fstream outUsersFile ("users.dat", ios::in | ios::out | ios::trunc | ios::binary); // ios::in will require an existing file
   // Uses: "users.dat", generated in previous example
   if (!outUsersFile) { // fstream could not open file
     cerr << "File could not be opened." << endl;
     exit (1);
   }
   int position = 0;
   for(it=dataBaseUser.begin(); it!=dataBaseUser.end(); it++){
     User user = *it;
     outUsersFile.seekp (position * sizeof (User));
     outUsersFile.write (reinterpret_cast <const char *> (&user), sizeof (User));
     position ++;
   }
 }
showAdminChoices()
void DataBase::showAdminChoices ()
Displays the manage users options menu, that only an Admin can use
Definition at line 130 of file DataBase.cpp.
{
   //displays the manage users options menu, that only an Admin can use
   while (true) {
     cout << "\n                             MANAGE USERS" << endl
       << "---------------------------------------------------------------------" << endl;
     cout << "                    1. ADD USER" << endl
         << "                    2. DELETE USER" << endl
         << "                    3. SHOW USERS LIST" << endl
         << "                    4. BACK TO MENU" << endl;
     cout << "Enter your choice number: ";
     cin >> choice;
     switch (choice)
     {
     case 1:
       cout << "Enter a new user" << endl;
       cout << "User number: ";
       cin >> userNumberStr;
       cout << "User password: ";
       cin >> NIFStr;
       cout << "User name: ";
       cin >> name;
       cout << "User type (1=Admin, 0=User): ";
       cin >> type;
       if (type == 1){
         isAdmin = true;
       }else{  isAdmin = false; }
       addUser(userNumberStr, NIFStr, name, isAdmin);
       break;
     case 2:
       cout << "Enter the user number that you want to delete: ";
       cin >> userNumber;
       deleteUser(userNumber);
       break;
     case 3:
       cout << "USERS LIST: " << endl;
       cout << "N\tNAME\t\tTYPE" << endl;
       showUsers();
       break;
     case 4:
       return;
       break;
     }
   }
 }
showUsers()
void DataBase::showUsers ()
Shows the users that are saved in the database
Definition at line 117 of file DataBase.cpp.
{
   //shows the users that are saved in the database
   for(it=dataBaseUser.begin(); it!=dataBaseUser.end(); it++){
     User user = *it;
     user.showUser();
     if(user.checkAdmin()){
       cout << "\t\tAdmin" << endl;
     }else{
       cout << "\t\tEmployee" << endl;
     }
   }
 }
References User::checkAdmin(), and User::showUser().
Member Data Documentation
choice
int DataBase::choice private
Definition at line 62 of file DataBase.h.
dataBaseUser
set<User> DataBase::dataBaseUser private
Definition at line 60 of file DataBase.h.
isAdmin
bool DataBase::isAdmin private
Definition at line 69 of file DataBase.h.
it
set<User>::iterator DataBase::it private
Definition at line 61 of file DataBase.h.
name
string DataBase::name private
Definition at line 67 of file DataBase.h.
NIF
int DataBase::NIF private
Definition at line 66 of file DataBase.h.
NIFStr
std::string DataBase::NIFStr private
Definition at line 64 of file DataBase.h.
type
int DataBase::type private
Definition at line 68 of file DataBase.h.
userDeleted
User DataBase::userDeleted
Definition at line 56 of file DataBase.h.
userNow
User DataBase::userNow
Definition at line 55 of file DataBase.h.
userNumber
int DataBase::userNumber private
Definition at line 65 of file DataBase.h.
userNumberStr
std::string DataBase::userNumberStr private
Definition at line 63 of file DataBase.h.
The documentation for this class was generated from the following files:
DataBase.h
DataBase.cpp